apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: java-app
    version: v1
    app.kubernetes.io/part-of: Canon-POC
  name: java-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-app
      version: v1
  template:
    metadata:
      labels:
        app: java-app
        version: v1
    spec:
      containers:
        - name: java-app
          image: image-registry.openshift-image-registry.svc:5000/$NAMESPACE/java-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9080
            - containerPort: 9443
          env:
          - name: spring_profiles_active
            valueFrom:
              configMapKeyRef:
                name: csmp-config
                key: spring_profiles_active
          - name: db_host
            valueFrom:
              secretKeyRef:
                name: csmp-secrets
                key: db_host
          - name: db_service
            valueFrom:
              secretKeyRef:
                name: csmp-secrets
                key: db_service
          - name: db_user
            valueFrom:
              secretKeyRef:
                name: csmp-secrets
                key: db_user
          - name: db_pswd
            valueFrom:
              secretKeyRef:
                name: csmp-secrets
                key: db_pswd
